export function debug (arg: String)
export function error (arg: String)
export function info (arg: String)
export function prompt (arg: String)
export function setColor (color: Boolean)
export function silly (arg: String)
export function verbose (arg: String)
export function warn (arg: String)
